import {
  AppWindow,
  Award,
  BookOpen,
  Briefcase,
  BriefcaseBusiness,
  Building,
  Code,
  Copy,
  Download,
  ExternalLink,
  FileText,
  FolderGit2,
  FolderOpen,
  GraduationCap,
  Handshake,
  HeartHandshake,
  House,
  Lock,
  Mail,
  Mic,
  PenLine,
  Rocket,
  Server,
  ShieldCheck,
  Smartphone,
  Sparkles,
  SunMoon,
  Trophy,
  User,
  Users,
  type LucideIcon,
} from 'lucide-react';

/**
 * Icons that data files may reference by name. Registering them explicitly keeps the bundle
 * small (importing lucide's full `icons` map would ship every icon). Add new names here first.
 */
export const iconRegistry = {
  AppWindow,
  Award,
  BookOpen,
  Briefcase,
  BriefcaseBusiness,
  Building,
  Code,
  Copy,
  Download,
  ExternalLink,
  FileText,
  FolderGit2,
  FolderOpen,
  GraduationCap,
  Handshake,
  HeartHandshake,
  House,
  Lock,
  Mail,
  Mic,
  PenLine,
  Rocket,
  Server,
  ShieldCheck,
  Smartphone,
  Sparkles,
  SunMoon,
  Trophy,
  User,
  Users,
} satisfies Record<string, LucideIcon>;

export type IconName = keyof typeof iconRegistry;
